---
- name: "create systemd service"
  template:
    src: "etc/systemd/system/systemd.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: 0664
  with_items: "{{ systemd_service | list }}"
  notify:
    - restart service
  tags:
    - systemd-service

- name: "create systemd target"
  template:
    src: "etc/systemd/system/systemd.target.j2"
    dest: "/etc/systemd/system/{{ item }}.target"
    mode: 0664
  with_items: "{{ systemd_target | list }}"
  tags:
    - systemd-service

- name: "enable service"
  systemd:
    name: "{{ item }}.service"
    enabled: "{{ systemd_service['item'].enabled | default(False) }}"
  with_items: "{{ systemd_service | list }}"
  tags:
    - systemd-service
